version: '3.4'

services:
  api:
    build:
      context: .
      target: build
    # image: league-api
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - '6379:6379'
